apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
#        - name: command-handler
#          image: username/customer-command-handler:latest
#          ports:
#            - containerPort: 8084
        - name: policy-handler
          image: username/customer-policy-handler:v1
