server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: drivercall
          uri: http://localhost:8081
          predicates:
            - Path=/drivercalls/** 
        - id: drivermanage
          uri: http://localhost:8082
          predicates:
            - Path=/drivermanages/** 
        - id: driverassign
          uri: http://localhost:8084
          predicates:
            - Path=/driverassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: drivercall
          uri: http://drivercall:8080
          predicates:
            - Path=/drivercalls/** 
        - id: taximanage
          uri: http://taximanage:8080
          predicates:
            - Path=/taximanages/** 
        - id: driverassign
          uri: http://localhost:8080
          predicates:
            - Path=/driverassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
